from pathlib import Path
import re

path = Path(__file__).resolve().parents[1] / "dashboard" / "index.html"
html = path.read_text(encoding="utf-8")
html = html.replace('65%,100%{transform:translateX(100%)}}50%{opacity:1;transform:scale(1.15)}}', '')
html = html.replace('.section[data-panel] .panel-tag{color:var(--faint);font-size:10px;font-weight:650;letter-spacing:.08em}', '.panel-tag{color:var(--faint);font-size:10px;font-weight:650;letter-spacing:.08em}')
needle = '<section class="card full"><div class="notice"><span class="negative">●</span><div><strong>H-SW1-CLAUDE · official method.</strong>'
replacement = '<section class="card full"><div class="notice"><span class="negative">●</span><div><strong>H-SW1 comparison is manual and read-only.</strong> Research RPCs are not part of the 15-second market refresh. Run the comparison only when you intentionally want a new frozen observation.</div><button id="runSw1" type="button" style="margin-left:auto;white-space:nowrap">Run comparison once</button></div><div class="footnote" id="sw1RunStatus">Not run in this browser session.</div><div class="notice" style="margin-top:12px"><span class="negative">●</span><div><strong>H-SW1-CLAUDE · official method.</strong>'
if needle not in html: raise SystemExit("H-SW1 section anchor not found")
if 'id="runSw1"' not in html: html = html.replace(needle, replacement, 1)
html = html.replace("const [h,o,s,l,f,r]=await Promise.all([get('/health'),get('/api/v1/market/ohlcv/latest?limit=3'),get('/api/v1/signal/hfb1/current'),get('/api/v1/signals/log?limit=30'),get('/api/v1/funding/latest'),get(researchUrl)]);", "const [h,o,s,l,f]=await Promise.all([get('/health'),get('/api/v1/market/ohlcv/latest?limit=3'),get('/api/v1/signal/hfb1/current'),get('/api/v1/signals/log?limit=30'),get('/api/v1/funding/latest')]);")
html = html.replace("const researchEndpoint='/api/v1/research/hfb1';const researchUrl=researchEndpoint;", "")
html = re.sub(r"const x=\(r\.data\|\|\)\[0\];if\(!x\).*?\}\s*function renderSw1Overall", "function renderSw1Overall", html, count=1, flags=re.S)
old_boot = 'updateClock();setInterval(updateClock,1000);load();setInterval(load,15000);'
new_boot = '''async function loadFrozenResearch(){try{const r=await get('/api/v1/research/hfb1');const x=(r.data||[])[0];$('hfb').innerHTML=x?`<tr><td data-label="N">${fmt(x.n,0)}</td><td data-label="Gross EV">${fmt(x.mean_gross_bps)}</td><td data-label="Net EV" class="${Number(x.mean_net_bps)>0?'positive':'negative'}">${fmt(x.mean_net_bps)}</td><td data-label="Win rate">${fmt(Number(x.win_rate)*100,2)}%</td><td data-label="Net 95% CI">${fmt(x.net_ci95_low)} → ${fmt(x.net_ci95_high)}</td><td data-label="Window">${iso(x.first_event_time_ms)} → ${iso(x.last_event_time_ms)}</td></tr>`:'<tr><td colspan="6">No H-FB1 result yet</td></tr>'}catch(e){$('hfb').innerHTML='<tr><td colspan="6">Research data unavailable</td></tr>'}}
async function runSw1Comparison(){const button=$('runSw1');const status=$('sw1RunStatus');button.disabled=true;button.textContent='Running once…';status.textContent='Reading both frozen RPCs at one cutoff…';try{const [claude,manus]=await Promise.all([get('/api/v1/research/sw1-claude'),get('/api/v1/research/sw1-manus')]);renderSw1Overall('sw1ClaudeOverall',claude);const manusRows=renderSw1Overall('sw1ManusOverall',manus);const quarters=manusRows.filter(x=>String(x.bucket||'').startsWith('quarter_'));$('sw1ManusQuarters').innerHTML=quarters.length?quarters.map(q=>`<tr><td data-label="Quarter">${q.bucket}</td><td data-label="N">${fmt(q.n,0)}</td><td data-label="Net EV" class="${Number(q.mean_net_bps)>0?'positive':'negative'}">${fmt(q.mean_net_bps)}</td><td data-label="Win rate">${fmt(Number(q.win_rate)*100,2)}%</td></tr>`).join(''):'<tr><td colspan="4">No Manus quarter data</td></tr>';status.textContent='Comparison complete · read-only · no execution';}catch(e){status.textContent='Comparison unavailable · no result fabricated';$('sw1ClaudeOverall').innerHTML='<tr><td colspan="6">Method unavailable</td></tr>';$('sw1ManusOverall').innerHTML='<tr><td colspan="6">Method unavailable</td></tr>';$('sw1ManusQuarters').innerHTML='<tr><td colspan="4">Method unavailable</td></tr>'}finally{button.disabled=false;button.textContent='Run comparison once'}}
$('runSw1').addEventListener('click',runSw1Comparison);updateClock();setInterval(updateClock,1000);load();loadFrozenResearch();setInterval(load,15000);'''
if old_boot not in html: raise SystemExit("bootstrap anchor not found")
html = html.replace(old_boot, new_boot, 1)
path.write_text(html, encoding="utf-8")
print("dashboard research polling fixed")
