from pathlib import Path

p = Path(__file__).resolve().parents[1] / 'dashboard' / 'index.html'
s = p.read_text(encoding='utf-8')

s = s.replace('<option value="exchange">Exchange</option><option value="institutional">Institutional</option><option value="research">Research</option>', '<option value="terminal">Terminal</option><option value="clean">Clean</option><option value="story">Story</option>')
s = s.replace('allowed=[\'exchange\',\'institutional\',\'research\']', "allowed=['terminal','clean','story']")
s = s.replace("localStorage.getItem('hyperhan-theme')||'exchange'", "localStorage.getItem('hyperhan-theme')||'terminal'")
s = s.replace('body[data-theme="institutional"]', 'body[data-theme="clean"]')
s = s.replace('body[data-theme="research"]', 'body[data-theme="story"]')
s = s.replace("get('/api/v1/market/ohlcv/latest?limit=3')", "get('/api/v1/market/ohlcv/latest?limit=24')")

css_start = s.index('/* Three local skins.')
css_end = s.index('</style>', css_start)
css = '''/* Three distinct presentation modes. Presentation only; no API or data mutation. */
#themeSelect{font:inherit;color:#eaecef;background:#181a20;border:1px solid #474d57;border-radius:4px;padding:7px 9px;font-size:11px;cursor:pointer}#themeSelect:focus{outline:1px solid #f0b90b;outline-offset:1px}
#chartPanel,#storyPanel{display:none}.chart-wrap{padding:14px 16px;background:var(--panel);border:1px solid var(--line);border-radius:4px}.chart-head{display:flex;justify-content:space-between;align-items:baseline;gap:12px;margin-bottom:12px}.chart-title{font-size:11px;font-weight:750;letter-spacing:.1em;text-transform:uppercase;color:var(--muted)}.chart-note{font-size:10px;color:var(--faint)}#marketChart{display:block;width:100%;height:170px}.chart-line{fill:none;stroke:var(--cyan);stroke-width:2.2;vector-effect:non-scaling-stroke}.chart-area{fill:var(--cyan);opacity:.08}.chart-grid{stroke:var(--line);stroke-width:1}.story-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1px;background:var(--line);border:1px solid var(--line)}.story-cell{padding:16px;background:var(--panel)}.story-label{color:var(--faint);font-size:10px;font-weight:750;letter-spacing:.1em;text-transform:uppercase}.story-value{margin-top:8px;color:var(--text,#eaecef);font-size:20px;font-weight:750}.story-copy{max-width:760px;color:var(--muted);font-size:12px;line-height:1.65}
body[data-theme="clean"]{--bg:#f5f5f2;--panel:#ffffff;--panel-2:#efefeb;--line:#d9d9d2;--line-bright:#a8a8a0;--muted:#686861;--faint:#8a8a82;--cyan:#ad6b00;--green:#18794e;--red:#b42318;--amber:#ad6b00;color:#171717;color-scheme:light}body[data-theme="clean"] header{background:#f5f5f2;border-bottom-color:#d9d9d2}body[data-theme="clean"] .mark{background:#fff;border-color:#ad6b00}body[data-theme="clean"] .title,body[data-theme="clean"] .card h2,body[data-theme="clean"] .section,body[data-theme="clean"] .notice strong{color:#171717}body[data-theme="clean"] .status,body[data-theme="clean"] #themeSelect{color:#171717;background:#fff;border-color:#a8a8a0}body[data-theme="clean"] .card,body[data-theme="clean"] .chart-wrap{border-radius:2px;background:#fff;box-shadow:none}body[data-theme="clean"] .notice{background:#f1f1ed;border-color:#d9d9d2;color:#4f4f49;border-radius:2px}body[data-theme="clean"] .table th{background:#efefeb;color:#686861}body[data-theme="clean"] .table td{color:#30302d;border-color:#e1e1da}body[data-theme="clean"] .sub,body[data-theme="clean"] .hero p,body[data-theme="clean"] .meta,body[data-theme="clean"] .footnote,body[data-theme="clean"] .utc-clock{color:#686861}body[data-theme="clean"] .price-card .value{color:#171717}body[data-theme="clean"] .exec-badge{color:#b42318}body[data-theme="clean"] #chartPanel{display:block}body[data-theme="clean"] .chart-wrap{border-color:#d9d9d2}body[data-theme="clean"] .chart-grid{stroke:#e1e1da}
body[data-theme="story"]{--bg:#111315;--panel:#17191c;--panel-2:#202328;--line:#34383e;--line-bright:#626a73;--muted:#a8afb7;--faint:#737b84;--cyan:#d9a441;--green:#8bc34a;--red:#d95757;--amber:#d9a441;color:#e8eaed}body[data-theme="story"] main{max-width:1180px;padding-top:34px}body[data-theme="story"] .card,body[data-theme="story"] .chart-wrap{border-radius:2px;padding:22px}body[data-theme="story"] .section{font-family:Georgia,serif;font-size:16px;font-weight:600;letter-spacing:0}body[data-theme="story"] .hero h1{font-family:Georgia,serif;font-weight:600;letter-spacing:-.025em}body[data-theme="story"] .hero p,body[data-theme="story"] .story-copy{font-family:Georgia,serif;font-size:14px}body[data-theme="story"] .notice{border-radius:2px;background:#1a1d21}body[data-theme="story"] #chartPanel,body[data-theme="story"] #storyPanel{display:block}body[data-theme="story"] .story-cell{background:#17191c}
@media(max-width:620px){#themeSelect{max-width:90px;padding:6px 5px}.story-grid{grid-template-columns:1fr}.chart-head{align-items:flex-start;flex-direction:column}}
'''
s = s[:css_start] + css + s[css_end:]

anchor = '<div class="section">H-FB1 post-mortem record'
insert = '''<section id="chartPanel" class="card full"><div class="chart-wrap"><div class="chart-head"><span class="chart-title">BTCUSDT · recent observations</span><span class="chart-note">Live OHLCV response · no new data source</span></div><svg id="marketChart" viewBox="0 0 800 170" role="img" aria-label="BTCUSDT recent close observations"><line class="chart-grid" x1="0" y1="20" x2="800" y2="20"/><line class="chart-grid" x1="0" y1="85" x2="800" y2="85"/><line class="chart-grid" x1="0" y1="150" x2="800" y2="150"/><path id="chartArea" class="chart-area"/><path id="chartLine" class="chart-line"/></svg><div class="chart-note" id="chartNote">Waiting for live OHLCV response.</div></div></section>
<section id="storyPanel" class="card full"><div class="story-copy"><strong>Research record.</strong> This view adds context to the same live evidence. It does not create a signal, alter the frozen ledger, or expose a private method.</div><div class="story-grid" style="margin-top:16px"><div class="story-cell"><div class="story-label">Observed candles</div><div id="storyCandles" class="story-value">—</div></div><div class="story-cell"><div class="story-label">Observed window</div><div id="storyWindow" class="story-value">—</div></div><div class="story-cell"><div class="story-label">Close change</div><div id="storyChange" class="story-value">—</div></div></div><div class="footnote">Values are computed from the current Binance-backed OHLCV response. No historical value is invented when the response is unavailable.</div></section>
'''
if 'id="chartPanel"' not in s:
    s = s.replace(anchor, insert + anchor, 1)

marker = 'function renderSw1Overall(id,payload)'
chart_fn = '''function renderMarketChart(rows){const data=(rows||[]).filter(x=>Number.isFinite(Number(x.close))).slice().reverse();if(data.length<2){$('chartNote').textContent='Insufficient live OHLCV response';return}const vals=data.map(x=>Number(x.close));const min=Math.min(...vals),max=Math.max(...vals),span=max-min||1;const pts=vals.map((v,i)=>`${(i/(vals.length-1))*800},${150-((v-min)/span)*130}`);$('chartLine').setAttribute('d','M '+pts.join(' L '));$('chartArea').setAttribute('d','M '+pts.join(' L ')+' L 800,150 L 0,150 Z');$('chartNote').textContent=`${data.length} candles · ${iso(data[0].open_time_ms)} → ${iso(data[data.length-1].open_time_ms)}`;$('storyCandles').textContent=fmt(data.length,0);$('storyWindow').textContent=`${iso(data[0].open_time_ms)} → ${iso(data[data.length-1].open_time_ms)}`;const change=((vals[vals.length-1]/vals[0])-1)*100;$('storyChange').textContent=(change>=0?'+':'')+fmt(change,3)+'%';$('storyChange').className='story-value '+(change>=0?'positive':'negative')}
'''
if 'function renderMarketChart' not in s:
    s = s.replace(marker, chart_fn + marker, 1)
s = s.replace("const c=(o.data||[])[0]||{};", "const c=(o.data||[])[0]||{};renderMarketChart(o.data||[]);")

p.write_text(s, encoding='utf-8')
print('three dashboard modes rebuilt')
