from pathlib import Path

path = Path(__file__).resolve().parents[1] / "dashboard" / "index.html"
html = path.read_text(encoding="utf-8")
old_css = ".pulse{height:86px;width:100%;display:block}.pulse path{fill:none;stroke:var(--cyan);stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round}.pulse line{stroke:#263852;stroke-width:1}.pulse-dot{fill:#cbd5e1}.pulse-meta{display:flex;justify-content:space-between;margin-top:7px;color:var(--muted);font-size:11px}.pulse-note{color:var(--faint);font-size:10px;margin-top:8px}"
new_css = ".telemetry{position:relative;overflow:hidden;padding:20px 21px 18px;background:linear-gradient(145deg,#101d31,#0a1220);border:1px solid #263b58;border-radius:18px;box-shadow:inset 0 1px #ffffff08,0 18px 50px #0004}.telemetry:before{content:\"\";position:absolute;inset:0;background:linear-gradient(115deg,transparent 0%,#67e8f908 45%,transparent 70%);transform:translateX(-100%);animation:telemetry-sweep 8s ease-in-out infinite;pointer-events:none}.telemetry-head{position:relative;display:flex;align-items:flex-start;justify-content:space-between;gap:18px;margin-bottom:14px}.telemetry-kicker{color:var(--cyan);font-size:10px;font-weight:850;letter-spacing:.16em;text-transform:uppercase}.telemetry-title{margin-top:5px;color:#edf3ff;font-size:17px;font-weight:800;letter-spacing:-.025em}.telemetry-status{display:inline-flex;align-items:center;gap:7px;color:#aebbd0;border:1px solid #2b405d;border-radius:999px;padding:7px 10px;font-size:10px;font-weight:750;white-space:nowrap}.telemetry-status i{width:6px;height:6px;border-radius:50%;background:var(--green);box-shadow:0 0 0 4px #5eead41c;animation:status-pulse 2.2s ease-in-out infinite}.pulse-shell{position:relative;height:142px;overflow:hidden;border:1px solid #1d3049;border-radius:13px;background:linear-gradient(180deg,#0d1829,#0a1321)}.pulse-shell:after{content:\"\";position:absolute;inset:0;background:repeating-linear-gradient(0deg,transparent 0,transparent 34px,#ffffff05 35px),linear-gradient(90deg,transparent 0,transparent 24.9%,#ffffff05 25%,transparent 25.2%,transparent 49.9%,#ffffff05 50%,transparent 50.2%,transparent 74.9%,#ffffff05 75%,transparent 75.2%);pointer-events:none}.pulse{height:100%;width:100%;display:block}.pulse path{fill:none;stroke:var(--cyan);stroke-width:2.5;stroke-linecap:round;stroke-linejoin:round;filter:drop-shadow(0 0 5px #67e8f966)}.pulse-area{fill:url(#pulseFill);opacity:.34}.pulse line{stroke:#263852;stroke-width:1}.pulse-dot{fill:#e7fbff;stroke:#67e8f9;stroke-width:3;filter:drop-shadow(0 0 5px #67e8f9)}.pulse-meta{position:relative;display:flex;justify-content:space-between;align-items:center;gap:12px;margin-top:11px;color:var(--muted);font-size:11px}.pulse-delta{color:#dbeafe;font-weight:750}.pulse-note{color:var(--faint);font-size:10px;margin-top:9px}@keyframes telemetry-sweep{0%,35%{transform:translateX(-100%)}65%,100%{transform:translateX(100%)}}@keyframes status-pulse{0%,100%{opacity:.55;transform:scale(.9)}50%{opacity:1;transform:scale(1.15)}}@media(max-width:620px){.telemetry{padding:16px}.telemetry-title{font-size:15px}.telemetry-status{padding:6px 8px;font-size:9px}.pulse-shell{height:122px}}"
if old_css not in html:
    raise SystemExit("old pulse CSS not found")
html = html.replace(old_css, new_css, 1)
old_markup = '<section class="card full"><svg class="pulse" id="evidencePulse" viewBox="0 0 600 86" role="img" aria-label="Recent BTCUSDT close evidence pulse"><line x1="0" y1="43" x2="600" y2="43"></line><path id="evidencePath" d=""></path><circle class="pulse-dot" id="evidenceDot" cx="0" cy="43" r="3"></circle></svg><div class="pulse-meta"><span id="pulseWindow">Awaiting backend candles</span><span id="pulseDelta">—</span></div><div class="pulse-note">Computed in the browser from the existing latest OHLCV response. No new endpoint, storage, or trading signal.</div></section>'
new_markup = '<section class="card full telemetry"><div class="telemetry-head"><div><div class="telemetry-kicker">Live evidence / OHLCV</div><div class="telemetry-title">Recent market observation</div></div><div class="telemetry-status"><i></i><span id="pulseStatus">UPDATING</span></div></div><div class="pulse-shell"><svg class="pulse" id="evidencePulse" viewBox="0 0 600 142" role="img" aria-label="Recent BTCUSDT close evidence pulse"><defs><linearGradient id="pulseFill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="#67e8f9" stop-opacity=".5"></stop><stop offset="1" stop-color="#67e8f9" stop-opacity="0"></stop></linearGradient></defs><line x1="0" y1="71" x2="600" y2="71"></line><path class="pulse-area" id="evidenceArea" d=""></path><path id="evidencePath" d=""></path><circle class="pulse-dot" id="evidenceDot" cx="0" cy="71" r="4"></circle></svg></div><div class="pulse-meta"><span id="pulseWindow">Awaiting backend candles</span><span class="pulse-delta" id="pulseDelta">—</span></div><div class="pulse-note">Browser-rendered from the existing latest OHLCV response. No new endpoint, storage, or trading signal.</div></section>'
if old_markup not in html:
    raise SystemExit("old pulse markup not found")
html = html.replace(old_markup, new_markup, 1)
old_fn = "function renderPulse(rows){const data=(rows||[]).slice().reverse().filter(x=>Number.isFinite(Number(x.close)));if(!data.length){$('pulseWindow').textContent='No backend candles';$('pulseDelta').textContent='—';$('evidencePath').setAttribute('d','');return}const values=data.map(x=>Number(x.close));const min=Math.min(...values),max=Math.max(...values),span=max-min||1;const points=values.map((v,i)=>[i*(600/Math.max(1,values.length-1)),72-((v-min)/span)*58]);$('evidencePath').setAttribute('d',points.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' '));const last=points[points.length-1];$('evidenceDot').setAttribute('cx',last[0]);$('evidenceDot').setAttribute('cy',last[1]);const delta=values.length>1?values[values.length-1]-values[0]:0;$('pulseWindow').textContent=iso(data[0].open_time_ms)+' → '+iso(data[data.length-1].open_time_ms);$('pulseDelta').textContent=(delta>=0?'+':'')+fmt(delta,2)+' close delta'}"
new_fn = "function renderPulse(rows){const data=(rows||[]).slice().reverse().filter(x=>Number.isFinite(Number(x.close)));if(!data.length){$('pulseWindow').textContent='No backend candles';$('pulseDelta').textContent='—';$('pulseStatus').textContent='NO DATA';$('evidencePath').setAttribute('d','');$('evidenceArea').setAttribute('d','');return}const values=data.map(x=>Number(x.close));const min=Math.min(...values),max=Math.max(...values),span=max-min||1;const points=values.map((v,i)=>[i*(600/Math.max(1,values.length-1)),116-((v-min)/span)*82]);const line=points.map((p,i)=>(i?'L':'M')+p[0].toFixed(1)+' '+p[1].toFixed(1)).join(' ');$('evidencePath').setAttribute('d',line);$('evidenceArea').setAttribute('d',line+' L '+points[points.length-1][0].toFixed(1)+' 142 L '+points[0][0].toFixed(1)+' 142 Z');const last=points[points.length-1];$('evidenceDot').setAttribute('cx',last[0]);$('evidenceDot').setAttribute('cy',last[1]);const delta=values.length>1?values[values.length-1]-values[0]:0;$('pulseWindow').textContent=iso(data[0].open_time_ms)+' → '+iso(data[data.length-1].open_time_ms);$('pulseDelta').textContent=(delta>=0?'+':'')+fmt(delta,2)+' close delta';$('pulseStatus').textContent='LIVE · '+data.length+' OBSERVATIONS'}"
if old_fn not in html:
    raise SystemExit("old renderPulse function not found")
html = html.replace(old_fn, new_fn, 1)
path.write_text(html, encoding="utf-8")
print("telemetry pulse refined")
