from pathlib import Path

path = Path(__file__).resolve().parents[1] / "dashboard" / "index.html"
html = path.read_text(encoding="utf-8")
start = html.index("<script>")
end = html.index("</script>", start)
js = r'''<script>
const $=id=>document.getElementById(id);
const fmt=(x,d=3)=>x==null||Number.isNaN(Number(x))?'—':Number(x).toLocaleString(undefined,{maximumFractionDigits:d});
async function get(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(u+' '+r.status);return r.json()}
function iso(ms){return ms?new Date(Number(ms)).toISOString().replace('T',' ').replace('.000Z',' UTC'):'—'}
function updateClock(){document.querySelectorAll('.utc-clock').forEach(el=>el.textContent='UTC '+new Date().toISOString().slice(11,19))}
function flash(id,next){const el=$(id);if(!el)return;const value=String(next);if(el.textContent!==value){el.classList.remove('updated');void el.offsetWidth;el.classList.add('updated')}el.textContent=next}
function renderSw1Overall(id,payload){const rows=payload?.data||[];const overall=rows.find(x=>x.bucket==='overall');$(id).innerHTML=overall?`<tr><td data-label="N">${fmt(overall.n,0)}</td><td data-label="Gross EV">${fmt(overall.mean_gross_bps)}</td><td data-label="Net EV" class="${Number(overall.mean_net_bps)>0?'positive':'negative'}">${fmt(overall.mean_net_bps)}</td><td data-label="Win rate">${fmt(Number(overall.win_rate)*100,2)}%</td><td data-label="Net 95% CI">${fmt(overall.net_ci95_low)} → ${fmt(overall.net_ci95_high)}</td><td data-label="Window">${iso(overall.first_entry_ms)} → ${iso(overall.last_entry_ms)}</td></tr>`:`<tr><td colspan="6">${payload?'No persisted result':'Method unavailable'}</td></tr>`;return rows}
async function load(){try{const [h,o,s,l,f]=await Promise.all([get('/health'),get('/api/v1/market/ohlcv/latest?limit=3'),get('/api/v1/signal/hfb1/current'),get('/api/v1/signals/log?limit=30'),get('/api/v1/funding/latest')]);const c=(o.data||[])[0]||{};flash('price',fmt(c.close,2));$('candleTime').textContent=iso(c.open_time_ms);$('oh').textContent=fmt(c.open,2)+' / '+fmt(c.high,2);$('lc').textContent=fmt(c.low,2)+' / '+fmt(c.close,2);$('signal').textContent=s.signal||'NONE';$('signal').className='value observed';$('funding').textContent=s.funding_rate==null?'—':fmt(Number(s.funding_rate)*100,5)+'%';$('maturity').textContent=s.maturity_time_ms?iso(s.maturity_time_ms):'—';flash('data',h.status==='ok'?'HEALTHY':'DEGRADED');$('age').textContent=h.feature_freshness?.age_ms!=null?fmt(h.feature_freshness.age_ms,0)+' ms feature age':'—';$('session').textContent=h.collector_session?.status||'—';$('dot').className='dot '+(h.status==='ok'?'ok':'warn');flash('status',h.status==='ok'?'LIVE EVIDENCE · HEALTHY':'LIVE EVIDENCE · DEGRADED');$('ohlcvState').textContent=o.data?.length?'OK · '+o.data.length+' candles':'NO DATA';$('fundingState').textContent=f.data?'OK · latest event '+iso(f.data.funding_time_ms):'NO FUNDING EVENTS';$('auditState').textContent=(l.data||[]).length+' captured H-FB1 events';$('pipelineState').textContent=h.status==='ok'?'HEALTHY':'DEGRADED';const rows=l.data||[];$('log').innerHTML=rows.length?rows.map(x=>`<tr><td data-label="Time">${iso(x.event_time_ms)}</td><td data-label="Direction" class="${x.direction==='LONG'?'positive':'negative'}">${x.direction}</td><td data-label="Status">${x.status}</td><td data-label="Funding rate">${x.feature_json?.funding_rate==null?'—':fmt(Number(x.feature_json.funding_rate)*100,5)+'%'}</td><td data-label="Source">${x.source}</td><td data-label="Rationale">${x.rationale||'—'}</td></tr>`).join(''):'<tr><td colspan="6">No captured H-FB1 events</td></tr>'}catch(e){$('dot').className='dot bad';$('status').textContent='API UNAVAILABLE';$('data').textContent='OFFLINE';$('age').textContent='—';$('session').textContent='—';$('ohlcvState').textContent='OFFLINE';$('fundingState').textContent='OFFLINE';$('auditState').textContent='OFFLINE';$('pipelineState').textContent='OFFLINE';$('log').innerHTML='<tr><td colspan="6">Signal log unavailable</td></tr>'}}
async function loadFrozenResearch(){try{const r=await get('/api/v1/research/hfb1');const x=(r.data||[])[0];$('hfb').innerHTML=x?`<tr><td data-label="N">${fmt(x.n,0)}</td><td data-label="Gross EV">${fmt(x.mean_gross_bps)}</td><td data-label="Net EV" class="${Number(x.mean_net_bps)>0?'positive':'negative'}">${fmt(x.mean_net_bps)}</td><td data-label="Win rate">${fmt(Number(x.win_rate)*100,2)}%</td><td data-label="Net 95% CI">${fmt(x.net_ci95_low)} → ${fmt(x.net_ci95_high)}</td><td data-label="Window">${iso(x.first_event_time_ms)} → ${iso(x.last_event_time_ms)}</td></tr>`:'<tr><td colspan="6">No H-FB1 result yet</td></tr>'}catch(e){$('hfb').innerHTML='<tr><td colspan="6">Research data unavailable</td></tr>'}}
async function runSw1Comparison(){const button=$('runSw1');const status=$('sw1RunStatus');button.disabled=true;button.textContent='Running once…';status.textContent='Reading both frozen RPCs at one cutoff…';try{const [claude,manus]=await Promise.all([get('/api/v1/research/sw1-claude'),get('/api/v1/research/sw1-manus')]);renderSw1Overall('sw1ClaudeOverall',claude);const rows=renderSw1Overall('sw1ManusOverall',manus);const quarters=rows.filter(x=>String(x.bucket||'').startsWith('quarter_'));$('sw1ManusQuarters').innerHTML=quarters.length?quarters.map(q=>`<tr><td data-label="Quarter">${q.bucket}</td><td data-label="N">${fmt(q.n,0)}</td><td data-label="Net EV" class="${Number(q.mean_net_bps)>0?'positive':'negative'}">${fmt(q.mean_net_bps)}</td><td data-label="Win rate">${fmt(Number(q.win_rate)*100,2)}%</td></tr>`).join(''):'<tr><td colspan="4">No Manus quarter data</td></tr>';status.textContent='Comparison complete · read-only · no execution'}catch(e){status.textContent='Comparison unavailable · no result fabricated';$('sw1ClaudeOverall').innerHTML='<tr><td colspan="6">Method unavailable</td></tr>';$('sw1ManusOverall').innerHTML='<tr><td colspan="6">Method unavailable</td></tr>';$('sw1ManusQuarters').innerHTML='<tr><td colspan="4">Method unavailable</td></tr>'}finally{button.disabled=false;button.textContent='Run comparison once'}}
$('runSw1').addEventListener('click',runSw1Comparison);updateClock();setInterval(updateClock,1000);load();loadFrozenResearch();setInterval(load,15000);
</script>'''
path.write_text(html[:start]+js+html[end+len('</script>'):], encoding='utf-8')
print('runtime replaced')
