from pathlib import Path

p=Path(__file__).resolve().parents[1]/'dashboard'/'index.html'
s=p.read_text(encoding='utf-8')
start=s.index('let activePage=')
end=s.index('</script>',start)
js=r'''let activePage='overview',timer=null;
function updateClock(){$('utc').textContent='UTC '+new Date().toISOString().slice(11,19)}
async function get(u){const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(u+' '+r.status);return r.json()}
function setHeader(h){$('dot').className='dot '+(h.status==='ok'?'ok':'warn');$('status').textContent=h.status==='ok'?'LIVE EVIDENCE · HEALTHY':'LIVE EVIDENCE · DEGRADED'}
function setHeaderOffline(){ $('dot').className='dot bad';$('status').textContent='RESOURCE UNAVAILABLE' }
function setPage(page){activePage=['overview','visual','story'].includes(page)?page:'overview';document.body.dataset.page=activePage;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+activePage));document.querySelectorAll('.page-nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===activePage));document.querySelectorAll('.ios-bottom button').forEach(x=>x.classList.toggle('active',x.dataset.page===activePage));try{localStorage.setItem('hyperhan-page',activePage)}catch(e){};loadPage();clearInterval(timer);timer=setInterval(loadPage,activePage==='overview'?15000:300000)}
function renderChart(rows){const data=(rows||[]).filter(x=>Number.isFinite(Number(x.close))).slice().reverse();if(data.length<2){$('visualChartNote').textContent='Insufficient OHLCV response';return}const vals=data.map(x=>Number(x.close)),min=Math.min(...vals),max=Math.max(...vals),span=max-min||1,pts=vals.map((v,i)=>`${i/(vals.length-1)*900},${230-(v-min)/span*190}`);$('chartLine').setAttribute('d','M '+pts.join(' L '));$('chartArea').setAttribute('d','M '+pts.join(' L ')+' L 900,230 L 0,230 Z');$('visualChartNote').textContent=`${data.length} candles · ${iso(data[0].open_time_ms)} → ${iso(data.at(-1).open_time_ms)}`;$('visualCandles').textContent=fmt(data.length,0);$('visualFirst').textContent=iso(data[0].open_time_ms);$('visualLast').textContent=iso(data.at(-1).open_time_ms);const change=(vals.at(-1)/vals[0]-1)*100;$('visualChange').textContent=(change>=0?'+':'')+fmt(change,3)+'%';$('visualChange').className=change>=0?'green':'red'}
function renderResult(prefix,payload){const x=(payload?.data||[]).find(x=>x.bucket==='overall');if(!x)return;$(prefix+'N').textContent=fmt(x.n,0);$(prefix+'Gross').textContent=fmt(x.mean_gross_bps);$(prefix+'Net').textContent=fmt(x.mean_net_bps);$(prefix+'Win').textContent=fmt(Number(x.win_rate)*100,2)+'%';$(prefix+'CI').textContent=fmt(x.net_ci95_low)+' → '+fmt(x.net_ci95_high)}
async function loadOverview(){try{const [h,o,s,l,f]=await Promise.all([get('/health'),get('/api/v1/market/ohlcv/latest?limit=1'),get('/api/v1/signal/hfb1/current'),get('/api/v1/signals/log?limit=30'),get('/api/v1/funding/latest')]);const c=(o.data||[])[0]||{};setHeader(h);$('price').textContent=fmt(c.close,2);$('candleTime').textContent=iso(c.open_time_ms);$('oh').textContent=fmt(c.open,2)+' / '+fmt(c.high,2);$('lc').textContent=fmt(c.low,2)+' / '+fmt(c.close,2);$('signal').textContent=s.signal||'NONE';$('funding').textContent=s.funding_rate==null?'—':fmt(Number(s.funding_rate)*100,5)+'%';$('maturity').textContent=s.maturity_time_ms?iso(s.maturity_time_ms):'—';$('data').textContent=h.status==='ok'?'HEALTHY':'DEGRADED';$('age').textContent=h.feature_freshness?.age_ms!=null?fmt(h.feature_freshness.age_ms,0)+' ms feature age':'—';$('session').textContent=h.collector_session?.status||'—';$('ohlcvState').textContent=o.data?.length?'OK · live candle':'NO DATA';$('fundingState').textContent=f.data?'OK · latest '+iso(f.data.funding_time_ms):'NO DATA';$('auditState').textContent=(l.data||[]).length+' captured events';$('pipelineState').textContent=h.status==='ok'?'HEALTHY':'DEGRADED';$('overviewFetched').textContent='Fetched '+new Date().toISOString().slice(11,19)+' UTC'}catch(e){setHeaderOffline();['price','signal','data','age','session','oh','lc','candleTime'].forEach(id=>$(id).textContent='UNAVAILABLE');['ohlcvState','fundingState','auditState','pipelineState'].forEach(id=>$(id).textContent='RESOURCE UNAVAILABLE')}}
async function loadVisual(){try{const [h,o]=await Promise.all([get('/health'),get('/api/v1/market/ohlcv/latest?limit=24')]);setHeader(h);renderChart(o.data||[])}catch(e){setHeaderOffline();$('visualChartNote').textContent='OHLCV resource unavailable';['visualCandles','visualFirst','visualLast','visualChange'].forEach(id=>$(id).textContent='UNAVAILABLE')}}
async function loadStory(){try{const [h,r,l,o]=await Promise.all([get('/health'),get('/api/v1/research/hfb1'),get('/api/v1/signals/log?limit=30'),get('/api/v1/market/ohlcv/latest?limit=1')]);const c=(o.data||[])[0]||{},x=(r.data||[])[0]||{};setHeader(h);$('storyPrice').textContent=fmt(c.close,2);$('storyHealth').textContent=h.status==='ok'?'HEALTHY':'DEGRADED';$('storyAudit').textContent=fmt((l.data||[]).length,0);$('storyDetail').textContent=x.n!=null?`Persisted research record · N ${fmt(x.n,0)} · net EV ${fmt(x.mean_net_bps)} bps · execution disabled`:'Backend healthy · no persisted result returned'}catch(e){setHeaderOffline();['storyPrice','storyHealth','storyAudit'].forEach(id=>$(id).textContent='UNAVAILABLE');$('storyDetail').textContent='Story resource unavailable; no result fabricated'}}
function loadPage(){if(activePage==='overview')return loadOverview();if(activePage==='visual')return loadVisual();return loadStory()}
async function loadFrozen(){const st=$('sw1RunStatus');st.textContent='Reading persisted frozen results…';try{const [a,b]=await Promise.all([get('/api/v1/research/sw1-claude'),get('/api/v1/research/sw1-manus')]);renderResult('ref',a);renderResult('ind',b);st.textContent='Comparison complete · read-only · no execution'}catch(e){st.textContent='Comparison unavailable · no result fabricated'}}
document.querySelectorAll('[data-page]').forEach(b=>b.addEventListener('click',()=>setPage(b.dataset.page)));$('runSw1').addEventListener('click',loadFrozen);let initial='overview';try{initial=localStorage.getItem('hyperhan-page')||'overview'}catch(e){}setPage(initial);setInterval(updateClock,1000);updateClock();
'''
s=s[:start]+js+s[end:]
p.write_text(s,encoding='utf-8')
print('page resource loaders split')
