-- Preregistered combined-paradigm research + persistent signal audit journal.
-- Hypothesis: extreme L2 imbalance has stronger directional expectancy when the
-- most recently CLOSED 1m candle has same-sign momentum. No threshold sweep.
-- This migration is intentionally separate from the live execution path.

CREATE TABLE IF NOT EXISTS public.signal_audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  session_id uuid NULL REFERENCES public.research_sessions(id) ON DELETE SET NULL,
  event_time_ms bigint NOT NULL,
  observed_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL CHECK (status IN ('NO_SIGNAL','PAPER_CANDIDATE','DEGRADED','ERROR')),
  direction text NOT NULL CHECK (direction IN ('LONG','SHORT','FLAT','NONE')),
  source text NOT NULL DEFAULT 'signal-engine',
  rationale text,
  gate_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  feature_json jsonb NOT NULL DEFAULT '{}'::jsonb,
  UNIQUE (event_time_ms, direction, source)
);

CREATE INDEX IF NOT EXISTS signal_audit_events_observed_idx
  ON public.signal_audit_events (observed_at DESC);
CREATE INDEX IF NOT EXISTS signal_audit_events_event_idx
  ON public.signal_audit_events (event_time_ms DESC);

ALTER TABLE public.signal_audit_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS signal_audit_events_read_public ON public.signal_audit_events;
CREATE POLICY signal_audit_events_read_public
  ON public.signal_audit_events FOR SELECT TO public USING (true);

-- Combined L2 + OHLCV mechanism. The 1m candle is required to be fully closed
-- before the feature event, preventing candle look-ahead.
CREATE OR REPLACE FUNCTION public.research_combined_alpha_scan_frozen(
  p_as_of_event_time_ms bigint,
  p_horizon_seconds integer DEFAULT 60,
  p_sample_limit integer DEFAULT 50000,
  p_purge_seconds integer DEFAULT 60,
  p_embargo_seconds integer DEFAULT 60,
  p_fee_bps numeric DEFAULT 0,
  p_slippage_bps numeric DEFAULT 0
)
RETURNS TABLE(
  hypothesis text,
  fold integer,
  test_n bigint,
  signal_n bigint,
  signal_rate numeric,
  mean_gross_bps numeric,
  mean_spread_bps numeric,
  mean_net_bps numeric,
  ci95_low numeric,
  ci95_high numeric
)
LANGUAGE sql STABLE AS $function$
WITH params AS (
  SELECT greatest(1,p_horizon_seconds)*1000 AS horizon_ms,
         greatest(0,p_purge_seconds)*1000 AS purge_ms,
         greatest(0,p_embargo_seconds)*1000 AS embargo_ms
),
entries AS (
  SELECT s.id, s.session_id, s.event_time_ms, s.mid_price, s.spread_bps,
         s.imbalance_1,
         c.open_time_ms AS candle_open_ms,
         10000.0*(c.close-c.open)/NULLIF(c.open,0) AS candle_return_bps
  FROM public.feature_snapshots s
  CROSS JOIN params p
  JOIN LATERAL (
    SELECT o.open_time_ms,o.open,o.close
    FROM public.ohlcv_1m o
    WHERE o.symbol='BTCUSDT'
      AND o.interval='1m'
      AND o.open_time_ms + 60000 <= s.event_time_ms
    ORDER BY o.open_time_ms DESC
    LIMIT 1
  ) c ON true
  WHERE s.symbol='BTCUSDT'
    AND s.event_time_ms <= p_as_of_event_time_ms-p.horizon_ms-3000
    AND s.mid_price > 0
    AND s.imbalance_1 IS NOT NULL
  ORDER BY s.event_time_ms DESC,s.id DESC
  LIMIT greatest(20000,least(p_sample_limit,200000))
),
labeled AS (
  SELECT e.*, f.mid_price AS future_mid,
         10000.0*(f.mid_price-e.mid_price)/e.mid_price AS ret_bps,
         ntile(5) OVER (ORDER BY e.event_time_ms,e.id) AS fold
  FROM entries e
  CROSS JOIN params p
  JOIN LATERAL (
    SELECT x.mid_price
    FROM public.feature_snapshots x
    WHERE x.symbol='BTCUSDT'
      AND x.session_id=e.session_id
      AND x.event_time_ms>=e.event_time_ms+p.horizon_ms
      AND x.event_time_ms<=e.event_time_ms+p.horizon_ms+3000
      AND x.mid_price>0
    ORDER BY x.event_time_ms,x.id
    LIMIT 1
  ) f ON true
),
bounds AS (
  SELECT fold,min(event_time_ms) AS test_start,count(*) AS test_n
  FROM labeled WHERE fold BETWEEN 2 AND 5 GROUP BY fold
),
train_q AS (
  SELECT b.fold,b.test_n,
         percentile_cont(.20) WITHIN GROUP (ORDER BY l.imbalance_1)
           FILTER (WHERE l.event_time_ms < b.test_start-p.purge_ms-p.embargo_ms) AS i20,
         percentile_cont(.80) WITHIN GROUP (ORDER BY l.imbalance_1)
           FILTER (WHERE l.event_time_ms < b.test_start-p.purge_ms-p.embargo_ms) AS i80
  FROM bounds b CROSS JOIN params p
  JOIN labeled l ON l.event_time_ms < b.test_start-p.purge_ms-p.embargo_ms
  GROUP BY b.fold,b.test_n,b.test_start,p.purge_ms,p.embargo_ms
),
scored AS (
  SELECT l.*,q.test_n,
    CASE
      WHEN l.imbalance_1>=q.i80 AND l.candle_return_bps>0 THEN 1
      WHEN l.imbalance_1<=q.i20 AND l.candle_return_bps<0 THEN -1
      ELSE 0
    END AS direction
  FROM labeled l JOIN train_q q ON q.fold=l.fold
),
signals AS (
  SELECT s.*,s.direction*s.ret_bps AS gross_bps,
         s.direction*s.ret_bps-(2*p_fee_bps+coalesce(s.spread_bps,0)+2*p_slippage_bps) AS net_bps
  FROM scored s WHERE s.direction<>0
),
stats AS (
  SELECT 'l2_imbalance_plus_closed_1m_momentum_agreement'::text AS hypothesis,
         s.fold,max(s.test_n) AS test_n,count(*) AS signal_n,
         avg(s.gross_bps) AS mean_gross_bps,
         avg(s.spread_bps) AS mean_spread_bps,
         avg(s.net_bps) AS mean_net_bps,
         avg(s.net_bps)-1.96*sqrt(greatest(0,coalesce(variance(s.net_bps),0))/nullif(count(*),0)) AS ci95_low,
         avg(s.net_bps)+1.96*sqrt(greatest(0,coalesce(variance(s.net_bps),0))/nullif(count(*),0)) AS ci95_high
  FROM signals s GROUP BY s.fold
)
SELECT hypothesis,fold,test_n,signal_n,
       signal_n::numeric/NULLIF(test_n,0),mean_gross_bps,mean_spread_bps,
       mean_net_bps,ci95_low,ci95_high
FROM stats ORDER BY fold;
$function$;

GRANT EXECUTE ON FUNCTION public.research_combined_alpha_scan_frozen(bigint,integer,integer,integer,integer,numeric,numeric) TO anon, authenticated, service_role;
