-- H-FB1: funding-rate sign at a completed funding event -> 240m hold.
-- Research unit is the funding event. Events are thinned so adjacent labels cannot
-- overlap the 240m horizon; no threshold or horizon search is performed.

CREATE TABLE IF NOT EXISTS public.funding_rate_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  symbol text NOT NULL,
  funding_time_ms bigint NOT NULL,
  funding_rate numeric NOT NULL,
  mark_price numeric,
  collected_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT funding_rate_events_unique UNIQUE (symbol, funding_time_ms)
);

ALTER TABLE public.funding_rate_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS funding_rate_events_select_public ON public.funding_rate_events;
CREATE POLICY funding_rate_events_select_public
  ON public.funding_rate_events
  FOR SELECT
  TO anon, authenticated
  USING (true);

GRANT SELECT ON public.funding_rate_events TO anon, authenticated;

CREATE INDEX IF NOT EXISTS funding_rate_events_symbol_time_idx
  ON public.funding_rate_events (symbol, funding_time_ms);

CREATE OR REPLACE FUNCTION public.research_funding_hfb1(
  p_oos_start_ms bigint,
  p_as_of_event_time_ms bigint,
  p_fee_bps numeric DEFAULT 4,
  p_slippage_bps numeric DEFAULT 1
)
RETURNS TABLE (
  horizon_minutes integer,
  n bigint,
  mean_gross_bps numeric,
  mean_net_bps numeric,
  win_rate numeric,
  net_ci95_low numeric,
  net_ci95_high numeric,
  first_event_time_ms bigint,
  last_event_time_ms bigint
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
WITH params AS (
  SELECT
    240::bigint * 60 * 1000 AS horizon_ms,
    greatest(0, p_fee_bps)::numeric AS fee_bps,
    greatest(0, p_slippage_bps)::numeric AS slippage_bps
),
ordered_events AS (
  SELECT
    e.symbol,
    e.funding_time_ms,
    e.funding_rate,
    lag(e.funding_time_ms) OVER (
      PARTITION BY e.symbol ORDER BY e.funding_time_ms
    ) AS previous_event_time_ms
  FROM funding_rate_events e
  WHERE e.symbol = 'BTCUSDT'
    AND e.funding_time_ms >= p_oos_start_ms
    AND e.funding_time_ms <= p_as_of_event_time_ms
),
non_overlapping_events AS (
  SELECT *
  FROM ordered_events o, params p
  WHERE o.previous_event_time_ms IS NULL
     OR o.funding_time_ms - o.previous_event_time_ms >= p.horizon_ms
),
entries AS (
  SELECT
    e.*,
    CASE
      WHEN e.funding_rate > 0 THEN 1
      WHEN e.funding_rate < 0 THEN -1
      ELSE 0
    END AS direction
  FROM non_overlapping_events e
),
valid_entries AS (
  SELECT e.*,
         entry_bar.open AS entry_price,
         exit_bar.close AS exit_price
  FROM entries e
  JOIN LATERAL (
    SELECT o.open
    FROM ohlcv_1m o
    WHERE o.symbol = e.symbol
      AND o.interval = '1m'
      AND o.open_time_ms >= e.funding_time_ms
      AND o.open > 0
    ORDER BY o.open_time_ms
    LIMIT 1
  ) entry_bar ON true
  JOIN LATERAL (
    SELECT o.close
    FROM ohlcv_1m o, params p
    WHERE o.symbol = e.symbol
      AND o.interval = '1m'
      AND o.open_time_ms >= e.funding_time_ms + p.horizon_ms
      AND o.close > 0
    ORDER BY o.open_time_ms
    LIMIT 1
  ) exit_bar ON true
  WHERE e.direction <> 0
),
scored AS (
  SELECT
    v.*,
    v.direction * 10000.0 * (v.exit_price - v.entry_price) / v.entry_price AS price_gross_bps,
    -v.direction * 10000.0 * COALESCE((
      SELECT sum(f.funding_rate)
      FROM funding_rate_events f
      WHERE f.symbol = v.symbol
        AND f.funding_time_ms > v.funding_time_ms
        AND f.funding_time_ms <= v.funding_time_ms + p.horizon_ms
    ), 0) AS funding_cashflow_bps
  FROM valid_entries v, params p
),
net AS (
  SELECT
    s.*,
    s.price_gross_bps + s.funding_cashflow_bps AS gross_bps,
    s.price_gross_bps + s.funding_cashflow_bps
      - 2 * (p.fee_bps + p.slippage_bps) AS net_bps
  FROM scored s, params p
),
stats AS (
  SELECT
    count(*)::bigint AS n,
    avg(gross_bps) AS mean_gross_bps,
    avg(net_bps) AS mean_net_bps,
    avg((net_bps > 0)::int)::numeric AS win_rate,
    sqrt(greatest(0, coalesce(variance(net_bps), 0)) / nullif(count(*), 0)) AS se_net,
    min(funding_time_ms) AS first_event_time_ms,
    max(funding_time_ms) AS last_event_time_ms
  FROM net
)
SELECT
  240::integer AS horizon_minutes,
  s.n,
  s.mean_gross_bps,
  s.mean_net_bps,
  s.win_rate,
  s.mean_net_bps - 1.96 * COALESCE(s.se_net, 0) AS net_ci95_low,
  s.mean_net_bps + 1.96 * COALESCE(s.se_net, 0) AS net_ci95_high,
  s.first_event_time_ms,
  s.last_event_time_ms
FROM stats s;

REVOKE ALL ON FUNCTION public.research_funding_hfb1(bigint, bigint, numeric, numeric) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.research_funding_hfb1(bigint, bigint, numeric, numeric) TO anon, authenticated;
